### ISSUE TITLE
jupyter-collaboration v3 with jupyterlab v4.5 is flooding the terminal with errors

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyter-collaboration#515]
## Description

I see many 
```
/api/collaboration/room/json:notebook:e0977c30-d773-46f5-b871-77a029000929?sessionId=fdd2b8d1-d820-4f04-a0a7-b2bdde674908', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/jupyter_server_ydoc/handlers.py", line 220, in get
        return await super().get(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/tornado/websocket.py", line 277, in get
        await self.ws_connection.accept_connection(self)
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/tornado/websocket.py", line 890, in accept_connection
        await self._accept_connection(handler)
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/tornado/websocket.py", line 973, in _accept_connection
        await self._receive_frame_loop()
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/tornado/websocket.py", line 1130, in _receive_frame_loop
        self.handler.on_ws_connection_close(self.close_code, self.close_reason)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/tornado/websocket.py", line 599, in on_ws_connection_close
        self.on_connection_close()
        ~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/tornado/websocket.py", line 591, in on_connection_close
        self.on_close()
        ~~~~~~~~~~~~~^^
      File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/jupyter_server_ydoc/handlers.py", line 324, in on_close
        if isinstance(self.room, DocumentRoom) and self.room.clients == [self]:
                      ^^^^^^^^^
    AttributeError: 'YDocWebSocketHandler' object has no attribute 'room'
[E 2025-11-20 10:26:19.642 YDocExtension] Jupyter Websocket Server:
      + Exception Group Traceback (most recent call last):
      |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/pycrdt_websocket/websocket_server.py", line 217, in start
      |     async with create_task_group() as self._task_group:
      |                ~~~~~~~~~~~~~~~~~^^
      |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/anyio/_backends/_asyncio.py", line 781, in __aexit__
      |     raise BaseExceptionGroup(
      |         "unhandled errors in a TaskGroup", self._exceptions
      |     ) from None
      | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
      +-+---------------- 1 ----------------
        | Exception Group Traceback (most recent call last):
        |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/pycrdt_websocket/yroom.py", line 226, in start
        |     async with create_task_group() as self._task_group:
        |                ~~~~~~~~~~~~~~~~~^^
        |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/anyio/_backends/_asyncio.py", line 781, in __aexit__
        |     raise BaseExceptionGroup(
        |         "unhandled errors in a TaskGroup", self._exceptions
        |     ) from None
        | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
        +-+---------------- 1 ----------------
          | Traceback (most recent call last):
          |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/jupyter_server_ydoc/rooms.py", line 206, in _broadcast_updates
          |     await super()._broadcast_updates()
          |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/pycrdt_websocket/yroom.py", line 148, in _broadcast_updates
          |     await self._task_group.start(self.ystore.start)
          |           ^^^^^^^^^^^^^^^^^^^^^^
          | AttributeError: 'NoneType' object has no attribute 'start'
          +------------------------------------
        | 
        | During handling of the above exception, another exception occurred:
        | 
        | Traceback (most recent call last):
        |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/pycrdt_websocket/yroom.py", line 239, in start
        |     await self.awareness.stop()
        |   File "/home/martin/micromamba/envs/test/lib/python3.14/site-packages/pycrdt/_awareness.py", line 99, in stop
        |     raise RuntimeError("Awareness not started")
        | RuntimeError: Awareness not started
```

## Reproduce

install jupyter-collaboration 3 with jupyterlab 4.5

**Comment by davidbrochart** [comment]
@jtpio mentioned that it could be caused by https://github.com/jupyterlab/jupyterlab/pull/15958, and I checked that it is indeed the case.

**Comment by kuldeep-surendra** [comment]
A notebook file was automatically deleted when the Real-Time Collaboration (RTC) system crashed with a RuntimeError: Awareness not started. The file deletion appears to be triggered by an overly aggressive error recovery mechanism that incorrectly includes physical file deletion as part of its cleanup process.

### Environment
jupyter-collaboration: 4.1.1
datalayer_pycrdt: 0.12.17
jupyterlab: 4.4.7
Python: 3.11
JupyterHub: (deployed in Kubernetes)



`Jupyter Websocket Server:\n      + Exception Group Traceback (most recent call last):\n      |   File \"/opt/conda/lib/python3.11/site-packages/pycrdt/websocket/websocket_server.py\", line 229, in start\n      |     async with create_task_group() as self._task_group:\n      |   File \"/opt/conda/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 781, in __aexit__\n      |     raise BaseExceptionGroup(\n      | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n      +-+---------------- 1 ----------------\n        | Exception Group Traceback (most recent call last):\n        |   File \"/opt/conda/lib/python3.11/site-packages/pycrdt/websocket/yroom.py\", line 234, in start\n        |     async with create_task_group() as self._task_group:\n        |   File \"/opt/conda/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 781, in __aexit__\n        |     raise BaseExceptionGroup(\n        | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)\n        +-+---------------- 1 ----------------\n          | Traceback (most recent call last):\n          |   File \"/opt/conda/lib/python3.11/site-packages/pycrdt/websocket/yroom.py\", line 235, in start\n          |     await self._start(task_status)\n          |   File \"/opt/conda/lib/python3.11/site-packages/pycrdt/websocket/yroom.py\", line 258, in _start\n          |     self._task_group.start_soon(self._run_provider)\n          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n          | AttributeError: 'NoneType' object has no attribute 'start_soon'\n          +---------------- 2 ----------------\n          | Traceback (most recent call last):\n          |   File \"/opt/conda/lib/python3.11/site-packages/jupyter_server_ydoc/rooms.py\", line 206, in _broadcast_updates\n          |     await super()._broadcast_updates()\n          |   File \"/opt/conda/lib/python3.11/site-packages/pycrdt/websocket/yroom.py\", line 165, in _broadcast_updates\n          |     await self._task_group.start(self.ystore.start)\n          |           ^^^^^^^^^^^^^^^^^^^^^^\n          | AttributeError: 'NoneType' object has no attribute 'start'\n          +------------------------------------\n        | \n        | During handling of the above exception, another exception occurred:\n        | \n        | Traceback (most recent call last):\n        |   File \"/opt/conda/lib/python3.11/site-packages/pycrdt/websocket/yroom.py\", line 238, in start\n        |     await self.awareness.stop()\n        |   File \"/opt/conda/lib/python3.11/site-packages/pycrdt/_awareness.py\", line 99, in stop\n        |     raise RuntimeError(\"Awareness not started\")\n        | RuntimeError: Awareness not started",`

**Comment by martinRenou** [comment]
> Also, just to spell it out, this can be worked around by upgrading to jupyter-collaboration v4

We discovered the issue with JupyterGIS which is currently stuck with jupyter-collaboration v3 until we sort out the ContentProvider concerns for lite (we don't want to make JupyterGIS incompatible with lite)

**Comment by savchenko** [comment]
I have just started seeing it:
```
IPython          : 9.10.0
ipykernel        : 7.2.0
ipywidgets       : 8.1.8
jupyter_client   : 8.8.0
jupyter_core     : 5.9.1
jupyter_server   : 2.18.2
jupyterlab       : 4.5.7
nbclient         : 0.10.4
nbconvert        : 7.17.0
nbformat         : 5.10.4
notebook         : 7.5.6
qtconsole        : not installed
traitlets        : 5.14.3
```

Wasn't a problem until very recently... Might have something to do with the `$PWD` content, etc?

**Comment by krassowski** [comment]
@savchenko is there something blocking you from upgrading to jupyter-collaboration v4?

**Comment by savchenko** [comment]
Ah, sorry, I am experiencing this with:
```
jupyter-collaboration         4.4.0
jupyter-collaboration-ui      2.4.0
```
